import type { LevelLayout } from "@/app/lib/game/types";

export const PLAYABLE_LEVEL_LAYOUT: LevelLayout = {
  id: "playable-level-001",
  title: "Level 1: Boarding Lane",
  metadata: {
    teachingFocus: "Learn to clear paths and fill vehicles at the boarding spot.",
  },
  boardSize: {
    rows: 6,
    cols: 6,
  },
  vehicles: [
    {
      id: "vehicle-red-1",
      color: "red",
      type: "minivan",
      seats: 2,
      boardedPassengers: 0,
      orientation: "horizontal",
      length: 2,
      cells: [
        { row: 0, col: 1 },
        { row: 0, col: 2 },
      ],
      exitLane: "right",
      location: "parking",
      dockSlotIndex: null,
    },
    {
      id: "vehicle-blue-1",
      color: "blue",
      type: "bus",
      seats: 3,
      boardedPassengers: 0,
      orientation: "vertical",
      length: 3,
      cells: [
        { row: 1, col: 0 },
        { row: 2, col: 0 },
        { row: 3, col: 0 },
      ],
      exitLane: "up",
      location: "parking",
      dockSlotIndex: null,
    },
    {
      id: "vehicle-green-1",
      color: "green",
      type: "minivan",
      seats: 2,
      boardedPassengers: 0,
      orientation: "horizontal",
      length: 2,
      cells: [
        { row: 2, col: 3 },
        { row: 2, col: 4 },
      ],
      exitLane: "left",
      location: "parking",
      dockSlotIndex: null,
    },
    {
      id: "vehicle-yellow-1",
      color: "yellow",
      type: "sedan",
      seats: 2,
      boardedPassengers: 0,
      orientation: "vertical",
      length: 2,
      cells: [
        { row: 3, col: 5 },
        { row: 4, col: 5 },
      ],
      exitLane: "down",
      location: "parking",
      dockSlotIndex: null,
    },
    {
      id: "vehicle-purple-1",
      color: "purple",
      type: "bus",
      seats: 3,
      boardedPassengers: 0,
      orientation: "horizontal",
      length: 3,
      cells: [
        { row: 4, col: 1 },
        { row: 4, col: 2 },
        { row: 4, col: 3 },
      ],
      exitLane: "right",
      location: "parking",
      dockSlotIndex: null,
    },
  ],
  // Simple queue: passengers grouped by color, each group size = vehicle seats
  // Total: 2+3+2+2+3 = 12 passengers
  initialPassengerQueue: [
    { id: "passenger-r1", color: "red", position: 0 },
    { id: "passenger-r2", color: "red", position: 1 },
    { id: "passenger-b1", color: "blue", position: 2 },
    { id: "passenger-b2", color: "blue", position: 3 },
    { id: "passenger-b3", color: "blue", position: 4 },
    { id: "passenger-g1", color: "green", position: 5 },
    { id: "passenger-g2", color: "green", position: 6 },
    { id: "passenger-y1", color: "yellow", position: 7 },
    { id: "passenger-y2", color: "yellow", position: 8 },
    { id: "passenger-p1", color: "purple", position: 9 },
    { id: "passenger-p2", color: "purple", position: 10 },
    { id: "passenger-p3", color: "purple", position: 11 },
  ],
  dockCapacity: 3,
};
