import type { LaunchLevelPack } from "./types";

export const LAUNCH_LEVEL_PACK: LaunchLevelPack = {
  packId: "launch",
  title: "Car Jam Color Tour",
  totalPlannedLevels: 10,
  levels: [
    {
      levelId: "tutorial-01",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["sun", "mint"],
      vehicles: [
        { id: "sun-1", x: 0, y: 3, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 1, skinKey: "coupe" },
        { id: "mint-1", x: 4, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "block-a", x: 0, y: 1, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 1, twoStars: 2, oneStar: 3 },
      themeId: "sunrise-lot",
      hintMetadata: { summary: "Slide the amber car into the open pickup column first.", recommendedFirstMove: { vehicleId: "sun-1", delta: 2 } },
    },
    {
      levelId: "tutorial-02",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["mint", "sun", "sun"],
      vehicles: [
        { id: "mint-1", x: 2, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "sun-1", x: 0, y: 4, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 2, skinKey: "coupe" },
        { id: "block-a", x: 2, y: 1, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 0, y: 2, length: 2, orientation: "horizontal", colorKey: "ocean", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 2, twoStars: 3, oneStar: 4 },
      themeId: "sunrise-lot",
      hintMetadata: { summary: "Free the mint shuttle, then clear the amber lane so the coupe can load both riders.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-03",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["ocean", "berry", "sun", "sun"],
      vehicles: [
        { id: "ocean-1", x: 0, y: 3, length: 2, orientation: "vertical", colorKey: "ocean", capacity: 1, skinKey: "mini" },
        { id: "berry-1", x: 3, y: 3, length: 2, orientation: "vertical", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "sun-1", x: 1, y: 4, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 2, skinKey: "coupe" },
        { id: "block-a", x: 0, y: 1, length: 2, orientation: "horizontal", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 3, y: 1, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
        { id: "block-c", x: 1, y: 2, length: 2, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 3, twoStars: 4, oneStar: 5 },
      themeId: "aquarium-lot",
      hintMetadata: { summary: "Open the left, then the right, then give the amber car a clean top column.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-04",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["berry", "mint", "berry", "gold"],
      vehicles: [
        { id: "berry-1", x: 0, y: 4, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 2, skinKey: "coupe" },
        { id: "mint-1", x: 3, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "gold-1", x: 4, y: 3, length: 2, orientation: "vertical", colorKey: "gold", capacity: 1, skinKey: "mini" },
        { id: "block-a", x: 0, y: 2, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 3, y: 1, length: 2, orientation: "horizontal", colorKey: "ocean", capacity: 1, skinKey: "mini" },
        { id: "block-c", x: 5, y: 1, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 3, twoStars: 5, oneStar: 6 },
      themeId: "aquarium-lot",
      hintMetadata: { summary: "Shift the berry coupe into a clear lane before solving the vertical pair on the right.", recommendedFirstMove: { vehicleId: "berry-1", delta: 2 } },
    },
    {
      levelId: "tutorial-05",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["coral", "sun", "mint", "sun", "plum"],
      vehicles: [
        { id: "coral-1", x: 1, y: 2, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
        { id: "sun-1", x: 2, y: 4, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 2, skinKey: "coupe" },
        { id: "mint-1", x: 5, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "plum-1", x: 1, y: 5, length: 3, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "van" },
        { id: "block-a", x: 0, y: 1, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 2, y: 2, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
        { id: "block-c", x: 4, y: 1, length: 2, orientation: "horizontal", colorKey: "ocean", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 4, twoStars: 5, oneStar: 7 },
      themeId: "arcade-lot",
      hintMetadata: { summary: "Send the coral compact first, then set up the amber two-seat car for a double boarding chain.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-06",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["coral", "sun", "mint", "sun", "plum", "gold"],
      vehicles: [
        { id: "coral-1", x: 1, y: 2, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
        { id: "sun-1", x: 2, y: 4, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 2, skinKey: "coupe" },
        { id: "mint-1", x: 5, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "plum-1", x: 1, y: 5, length: 2, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "mini" },
        { id: "gold-1", x: 3, y: 5, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
        { id: "block-a", x: 0, y: 1, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 2, y: 2, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
        { id: "block-c", x: 4, y: 1, length: 2, orientation: "horizontal", colorKey: "ocean", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 4, twoStars: 6, oneStar: 8 },
      themeId: "arcade-lot",
      hintMetadata: { summary: "Let the coral car go first, then reuse the newly opened upper lanes to chain the later passengers.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-07",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["plum", "sun", "coral", "mint", "berry", "ocean"],
      vehicles: [
        { id: "plum-1", x: 0, y: 5, length: 3, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "van" },
        { id: "sun-1", x: 4, y: 3, length: 2, orientation: "vertical", colorKey: "sun", capacity: 1, skinKey: "mini" },
        { id: "coral-1", x: 0, y: 3, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
        { id: "mint-1", x: 2, y: 4, length: 2, orientation: "horizontal", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "berry-1", x: 3, y: 5, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "ocean-1", x: 5, y: 0, length: 3, orientation: "vertical", colorKey: "ocean", capacity: 1, skinKey: "bus" },
        { id: "block-a", x: 0, y: 2, length: 3, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "van" },
        { id: "block-b", x: 2, y: 1, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 5, twoStars: 7, oneStar: 9 },
      themeId: "festival-lot",
      hintMetadata: { summary: "Use the long plum van after sliding the row blocker away from the left lanes.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-08",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["plum", "sun", "coral", "mint", "berry", "ocean", "mint"],
      vehicles: [
        { id: "plum-1", x: 0, y: 5, length: 3, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "van" },
        { id: "sun-1", x: 4, y: 3, length: 2, orientation: "vertical", colorKey: "sun", capacity: 1, skinKey: "mini" },
        { id: "coral-1", x: 0, y: 3, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
        { id: "mint-1", x: 2, y: 4, length: 2, orientation: "horizontal", colorKey: "mint", capacity: 2, skinKey: "coupe" },
        { id: "berry-1", x: 3, y: 5, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "ocean-1", x: 5, y: 0, length: 3, orientation: "vertical", colorKey: "ocean", capacity: 1, skinKey: "bus" },
        { id: "block-a", x: 0, y: 2, length: 3, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "van" },
        { id: "block-b", x: 2, y: 1, length: 2, orientation: "horizontal", colorKey: "gold", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 6, twoStars: 8, oneStar: 10 },
      themeId: "festival-lot",
      hintMetadata: { summary: "Open the left lanes first, then keep the mint coupe alive long enough to take both mint riders.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-09",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["ocean", "berry", "gold", "sun", "mint", "coral", "plum", "gold"],
      vehicles: [
        { id: "ocean-1", x: 0, y: 3, length: 2, orientation: "vertical", colorKey: "ocean", capacity: 1, skinKey: "mini" },
        { id: "berry-1", x: 2, y: 4, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "gold-1", x: 3, y: 5, length: 3, orientation: "horizontal", colorKey: "gold", capacity: 2, skinKey: "van" },
        { id: "sun-1", x: 4, y: 3, length: 2, orientation: "vertical", colorKey: "sun", capacity: 1, skinKey: "mini" },
        { id: "mint-1", x: 1, y: 5, length: 2, orientation: "horizontal", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "coral-1", x: 5, y: 0, length: 3, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "bus" },
        { id: "plum-1", x: 0, y: 1, length: 3, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "van" },
        { id: "block-a", x: 0, y: 2, length: 2, orientation: "horizontal", colorKey: "sun", capacity: 1, skinKey: "mini" },
        { id: "block-b", x: 3, y: 1, length: 2, orientation: "horizontal", colorKey: "mint", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 7, twoStars: 9, oneStar: 11 },
      themeId: "festival-lot",
      hintMetadata: { summary: "Open the ocean lane first; the two-passenger gold wagon can finish in one burst once it finds a clean column.", recommendedFirstMove: { vehicleId: "block-a", delta: 2 } },
    },
    {
      levelId: "tutorial-10",
      boardWidth: 6,
      boardHeight: 6,
      passengerQueue: ["sun", "mint", "berry", "gold", "coral", "plum", "ocean", "gold", "sun"],
      vehicles: [
        { id: "sun-1", x: 0, y: 4, length: 3, orientation: "horizontal", colorKey: "sun", capacity: 2, skinKey: "van" },
        { id: "mint-1", x: 3, y: 3, length: 2, orientation: "vertical", colorKey: "mint", capacity: 1, skinKey: "mini" },
        { id: "berry-1", x: 1, y: 3, length: 2, orientation: "horizontal", colorKey: "berry", capacity: 1, skinKey: "mini" },
        { id: "gold-1", x: 3, y: 5, length: 3, orientation: "horizontal", colorKey: "gold", capacity: 2, skinKey: "van" },
        { id: "coral-1", x: 5, y: 2, length: 2, orientation: "vertical", colorKey: "coral", capacity: 1, skinKey: "mini" },
        { id: "plum-1", x: 0, y: 1, length: 3, orientation: "horizontal", colorKey: "plum", capacity: 1, skinKey: "van" },
        { id: "ocean-1", x: 4, y: 0, length: 3, orientation: "vertical", colorKey: "ocean", capacity: 1, skinKey: "bus" },
        { id: "block-a", x: 0, y: 2, length: 3, orientation: "horizontal", colorKey: "mint", capacity: 1, skinKey: "van" },
        { id: "block-b", x: 0, y: 0, length: 2, orientation: "horizontal", colorKey: "coral", capacity: 1, skinKey: "mini" },
      ],
      starThresholds: { threeStars: 8, twoStars: 10, oneStar: 12 },
      themeId: "festival-lot",
      hintMetadata: { summary: "Break the first amber lane open and keep the center clear so the double-seat wagons can finish late in the sequence.", recommendedFirstMove: { vehicleId: "block-a", delta: 1 } },
    },
  ],
};
