import type { LaunchLevelPack } from "./types";

export const LAUNCH_LEVEL_PACK: LaunchLevelPack = {
  packId: "launch",
  title: "Pika Parking School",
  totalPlannedLevels: 30,
  levels: [
    {
      levelId: "tutorial-01",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 0, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "wagon-a", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "mint" },
        { id: "wagon-b", x: 3, y: 4, length: 2, orientation: "vertical", role: "car", facing: "down", colorKey: "berry" },
      ],
      starThresholds: { threeStars: 1, twoStars: 2, oneStar: 3 },
      themeId: "sunny-lot",
      hintMetadata: {
        summary: "The red car can drive straight to the gate.",
        focusVehicleIds: ["target"],
        recommendedFirstMove: { vehicleId: "target", distance: 4 },
      },
    },
    {
      levelId: "tutorial-02",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 1, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "blocker", x: 4, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "ocean" },
        { id: "wagon-a", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "mint" },
        { id: "wagon-b", x: 2, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "berry" },
      ],
      starThresholds: { threeStars: 2, twoStars: 3, oneStar: 4 },
      themeId: "sunny-lot",
      hintMetadata: {
        summary: "Nudge the tall blue car up to clear the lane, then let the target car leave.",
        focusVehicleIds: ["blocker", "target"],
        recommendedFirstMove: { vehicleId: "blocker", distance: 1 },
      },
    },
    {
      levelId: "tutorial-03",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 1, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "blocker-a", x: 3, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "ocean" },
        { id: "blocker-b", x: 5, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "berry" },
        { id: "wagon-a", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "mint" },
        { id: "wagon-b", x: 0, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "gold" },
      ],
      starThresholds: { threeStars: 3, twoStars: 4, oneStar: 5 },
      themeId: "sunny-lot",
      hintMetadata: {
        summary: "Clear the nearer blocker first, then the edge blocker.",
        focusVehicleIds: ["blocker-a", "blocker-b", "target"],
        recommendedFirstMove: { vehicleId: "blocker-a", distance: 3 },
      },
    },
    {
      levelId: "tutorial-04",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 0, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "blocker-a", x: 2, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "ocean" },
        { id: "blocker-b", x: 4, y: 2, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "berry" },
        { id: "helper", x: 1, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "mint" },
        { id: "wagon-a", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "gold" },
      ],
      starThresholds: { threeStars: 3, twoStars: 4, oneStar: 6 },
      themeId: "play-street",
      hintMetadata: {
        summary: "Lift the first blocker, raise the second even higher, and then slide out.",
        focusVehicleIds: ["blocker-a", "blocker-b", "target"],
        recommendedFirstMove: { vehicleId: "blocker-a", distance: 1 },
      },
    },
    {
      levelId: "tutorial-05",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 1, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "blocker-a", x: 3, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "ocean" },
        { id: "blocker-b", x: 4, y: 2, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "berry" },
        { id: "helper-a", x: 0, y: 3, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "mint" },
        { id: "helper-b", x: 2, y: 5, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "gold" },
      ],
      starThresholds: { threeStars: 4, twoStars: 5, oneStar: 7 },
      themeId: "play-street",
      hintMetadata: {
        summary: "Start by lifting the short blocker so the larger truck can drop later.",
        focusVehicleIds: ["blocker-a", "blocker-b", "target"],
        recommendedFirstMove: { vehicleId: "blocker-b", distance: 2 },
      },
    },
    {
      levelId: "tutorial-06",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 0, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "column-a", x: 2, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "ocean" },
        { id: "column-b", x: 4, y: 1, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "berry" },
        { id: "slider", x: 2, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "mint" },
        { id: "wagon-a", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "gold" },
        { id: "wagon-b", x: 0, y: 5, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "plum" },
      ],
      starThresholds: { threeStars: 4, twoStars: 6, oneStar: 8 },
      themeId: "play-street",
      hintMetadata: {
        summary: "Drop the right column first, then use the bottom lane to move the center truck.",
        focusVehicleIds: ["slider", "column-a", "column-b", "target"],
        recommendedFirstMove: { vehicleId: "column-b", distance: 2 },
      },
    },
    {
      levelId: "tutorial-07",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 1, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "column-a", x: 3, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "ocean" },
        { id: "column-b", x: 4, y: 2, length: 2, orientation: "vertical", role: "car", facing: "down", colorKey: "berry" },
        { id: "column-c", x: 5, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "gold" },
        { id: "row-a", x: 2, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "mint" },
        { id: "row-b", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "plum" },
      ],
      starThresholds: { threeStars: 5, twoStars: 6, oneStar: 8 },
      themeId: "neon-garage",
      hintMetadata: {
        summary: "Lift the left blocker first, then keep clearing the lane toward the exit.",
        focusVehicleIds: ["column-a", "column-b", "column-c", "target"],
        recommendedFirstMove: { vehicleId: "column-a", distance: 1 },
      },
    },
    {
      levelId: "tutorial-08",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 0, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "column-a", x: 2, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "ocean" },
        { id: "column-b", x: 3, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "berry" },
        { id: "column-c", x: 5, y: 2, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "gold" },
        { id: "row-a", x: 2, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "mint" },
        { id: "row-b", x: 0, y: 5, length: 3, orientation: "horizontal", role: "truck", facing: "right", colorKey: "plum" },
      ],
      starThresholds: { threeStars: 5, twoStars: 7, oneStar: 9 },
      themeId: "neon-garage",
      hintMetadata: {
        summary: "Start by lifting the nearest blocker, then clear the far edge.",
        focusVehicleIds: ["row-a", "column-b", "column-c", "target"],
        recommendedFirstMove: { vehicleId: "column-a", distance: 1 },
      },
    },
    {
      levelId: "tutorial-09",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 1, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "column-a", x: 3, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "ocean" },
        { id: "column-b", x: 4, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "berry" },
        { id: "column-c", x: 5, y: 2, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "gold" },
        { id: "row-a", x: 0, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "mint" },
        { id: "row-b", x: 2, y: 5, length: 3, orientation: "horizontal", role: "truck", facing: "right", colorKey: "plum" },
        { id: "row-c", x: 0, y: 0, length: 2, orientation: "horizontal", role: "car", facing: "left", colorKey: "coral" },
      ],
      starThresholds: { threeStars: 6, twoStars: 7, oneStar: 9 },
      themeId: "neon-garage",
      hintMetadata: {
        summary: "Lift the middle blocker first, then peel the others away in order.",
        focusVehicleIds: ["row-a", "column-a", "column-b", "column-c", "target"],
        recommendedFirstMove: { vehicleId: "column-b", distance: 1 },
      },
    },
    {
      levelId: "tutorial-10",
      boardWidth: 6,
      boardHeight: 6,
      exit: { side: "right", row: 2 },
      targetVehicleId: "target",
      vehicles: [
        { id: "target", x: 0, y: 2, length: 2, orientation: "horizontal", role: "target", facing: "right", colorKey: "sun" },
        { id: "column-a", x: 2, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "ocean" },
        { id: "column-b", x: 3, y: 1, length: 2, orientation: "vertical", role: "car", facing: "up", colorKey: "berry" },
        { id: "column-c", x: 4, y: 2, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "gold" },
        { id: "column-d", x: 5, y: 0, length: 3, orientation: "vertical", role: "truck", facing: "down", colorKey: "coral" },
        { id: "row-a", x: 1, y: 4, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "mint" },
        { id: "row-b", x: 3, y: 5, length: 2, orientation: "horizontal", role: "car", facing: "right", colorKey: "plum" },
      ],
      starThresholds: { threeStars: 6, twoStars: 8, oneStar: 10 },
      themeId: "moon-festival",
      hintMetadata: {
        summary: "Lift the short center blocker first before opening the lower lanes.",
        focusVehicleIds: ["row-a", "column-a", "column-b", "column-c", "target"],
        recommendedFirstMove: { vehicleId: "column-b", distance: 1 },
      },
    },
  ],
};
